### ISSUE TITLE
OSX Issues

### ISSUE THREAD

**Issue by rhaamo** [ImpalerWrG/Khazad#15]
I will create this issue for OSX issues.

I've restarted, i'm on commit 74c29337d8902ed3f1f186ce75a6e7d83ad066e3 right now.

Build pass:
```
ant -f /Users/dashie/dev/Khazad clean jar
init:
deps-clean:
Updating property file: /Users/dashie/dev/Khazad/build/built-clean.properties
Deleting directory /Users/dashie/dev/Khazad/build
clean:
Building jar: /Users/dashie/dev/Khazad/build/assets.jar
init:
deps-jar:
Updating property file: /Users/dashie/dev/Khazad/build/built-jar.properties
Created dir: /Users/dashie/dev/Khazad/build/classes
Created dir: /Users/dashie/dev/Khazad/build/empty
Compiling 99 source files to /Users/dashie/dev/Khazad/build/classes
warning: [options] bootstrap class path not set in conjunction with -source 1.5
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
compile:
Created dir: /Users/dashie/dev/Khazad/dist
Copying 1 file to /Users/dashie/dev/Khazad/build
Not copying library /Users/dashie/dev/Khazad/# Space-separated list of extra javac options , it can't be read.
Not copying library /Users/dashie/dev/Khazad/javac.compilerargs= , it can't be read.
Copy libraries to /Users/dashie/dev/Khazad/dist/lib.
Building jar: /Users/dashie/dev/Khazad/dist/Khazad.jar
To run this application from the command line without Ant, try:
java -jar "/Users/dashie/dev/Khazad/dist/Khazad.jar"
Linux Launcher Creation
Building zip: /Users/dashie/dev/Khazad/dist/Khazad-Linux.zip
Deleting: /Users/dashie/dev/Khazad/Khazad.sh
MacOSX Application Creation
Do not set property jfxdeploy.jvmargs as its length is 0.
Copying 1 file to /Users/dashie/dev/Khazad/resources/macapp
Building zip: /Users/dashie/dev/Khazad/dist/Khazad-MacOSX.zip
Deleting: /Users/dashie/dev/Khazad/resources/macapp/_Info.plist
Windows EXE Creation
Copying 1 file to /Users/dashie/dev/Khazad
Compiling resources
Linking
Wrapping
Successfully created /Users/dashie/dev/Khazad/dist/Khazad.exe
Deleting: /Users/dashie/dev/Khazad/launch4j-config.xml
Building zip: /Users/dashie/dev/Khazad/dist/Khazad-Windows.zip
Deleting: /Users/dashie/dev/Khazad/dist/Khazad.exe
jar:
BUILD SUCCESSFUL (total time: 13 seconds)
```

But run throw exception:
```
run:
avr. 09, 2015 12:38:26 PM com.jme3.system.JmeDesktopSystem initialize
Infos: Running on jMonkeyEngine 3.0.5
avr. 09, 2015 12:38:26 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
Infos: Lwjgl 2.9.0 context running on thread LWJGL Renderer Thread
avr. 09, 2015 12:38:26 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
Infos: Adapter: null
avr. 09, 2015 12:38:26 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
Infos: Driver Version: null
avr. 09, 2015 12:38:26 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
Infos: Vendor: Intel Inc.
avr. 09, 2015 12:38:26 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
Infos: OpenGL Version: 2.1 INTEL-10.6.20
avr. 09, 2015 12:38:26 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
Infos: Renderer: Intel HD Graphics 5000 OpenGL Engine
avr. 09, 2015 12:38:26 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
Infos: GLSL Ver: 1.20
avr. 09, 2015 12:38:27 PM com.jme3.asset.AssetConfig loadText
Avertissement: Cannot find loader com.jme3.scene.plugins.blender.BlenderModelLoader
avr. 09, 2015 12:38:27 PM com.jme3.audio.lwjgl.LwjglAudioRenderer initInThread
Infos: Audio Device: OpenAL Soft
avr. 09, 2015 12:38:27 PM com.jme3.audio.lwjgl.LwjglAudioRenderer initInThread
Infos: Audio Vendor: OpenAL Community
avr. 09, 2015 12:38:27 PM com.jme3.audio.lwjgl.LwjglAudioRenderer initInThread
Infos: Audio Renderer: OpenAL Soft
avr. 09, 2015 12:38:27 PM com.jme3.audio.lwjgl.LwjglAudioRenderer initInThread
Infos: Audio Version: 1.1 ALSOFT 1.15.1
avr. 09, 2015 12:38:27 PM com.jme3.audio.lwjgl.LwjglAudioRenderer initInThread
Infos: AudioRenderer supports 64 channels
avr. 09, 2015 12:38:27 PM com.jme3.audio.lwjgl.LwjglAudioRenderer initInThread
Infos: Audio effect extension version: 1.0
avr. 09, 2015 12:38:27 PM com.jme3.audio.lwjgl.LwjglAudioRenderer initInThread
Infos: Audio max auxilary sends: 4
avr. 09, 2015 12:38:27 PM com.jme3.app.Application handleError
Grave: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:400)
	at java.util.ArrayList.get(ArrayList.java:413)
	at Data.DataManager.getTextureData(DataManager.java:64)
	at Renderer.ImageManager.initialize(ImageManager.java:91)
	at Core.Main.simpleInitApp(Main.java:103)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:226)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:207)
	at java.lang.Thread.run(Thread.java:744)
```

When it start, it show jMe startup screen, use default settings (800x600 etc.) and launch then throw exception.

I'm not familiar with jMe nor java and at work ATM, but i can try to look how it is possible to debug that (if you have any hints !) when home.

**Comment by ImpalerWrG** [comment]
Thx for second Mac test, I was afraid this issue would manifest on Mac as it has on linux and it is good to have it confirmed.  After I emailed you a linux tester was able to find the bad file separators, some were in code and some in XML, his fix is posted at http://forum.freegamedev.net/viewtopic.php?f=22&t=6170#p63548

This is a quick fix of just manually fixing all the bad paths, rather then the run-time path scrubber I'd been planning, but if you like give it a try on your end and see if it works for Mac as well, remember to try to load and save the game (new features) as well as launch.

**Comment by ImpalerWrG** [comment]
To save you some time I have implemented the quick fix on the master branch, in commit 24a94cf24fcec7a2186dd0ea359977d67d34be02 please confirm if this works on your end now.
